name: lint-format-test-secure

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci

      # Lint and format code
      - name: Run ESLint
        run: npx eslint . --max-warnings=0

      - name: Run Prettier
        run: npx prettier --check .

      - name: Run build
        run: npm run build --if-present

      - name: Run tests
        run: npm test

  snyk:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js for Snyk
        uses: actions/setup-node@v4
        with:
          node-version: "18" # Or any other version you need
          cache: "npm"

      - run: npm ci

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk test
        run: snyk test

      - name: Run Snyk monitor
        run: snyk monitor
