name: Lint, Format, Type Check, Test & Secure

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Lint with ESLint
        run: npm run lint

      - name: Check Prettier Formatting
        run: npm run format:check

      - name: Type Check
        run: npm run tsc

      - name: Build Project
        run: npm run build

      - name: Generate Sitemap (Post-build)
        run: npm run postbuild

      - name: Run Tests
        run: npm test

      - name: Cache Next.js Build (optional)
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

  snyk-security:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Check if SNYK_TOKEN is Set
        run: |
          if [ -z "${{ secrets.SNYK_TOKEN }}" ]; then
            echo "SNYK_TOKEN is not set, skipping Snyk step."
            exit 0
          fi
        shell: bash

      - name: Authenticate with Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk auth $SNYK_TOKEN || (echo "Snyk auth failed, skipping..." && exit 0)

      - name: Run Snyk Security Test (Non-Blocking)
        run: |
          snyk test --severity-threshold=high || echo "Snyk test found issues, continuing..."

      - name: Monitor Snyk for Continuous Scanning (Non-Blocking)
        run: |
          snyk monitor || echo "Snyk monitor failed, continuing..."
