name: Lint, Format, Test & Secure

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # ✅ Define Node.js version (adjust as needed)
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Prettier (Auto-Fix)
        run: npm run format # ✅ Uses your package.json script

      - name: Check Formatting with Prettier
        run: npm run lint # ✅ Uses your package.json script

      - name: Build Project
        run: npm run build

      - name: Generate Sitemap (Post-build)
        run: npm run postbuild # ✅ Runs next-sitemap after build

      - name: Run Tests
        run: npm test

  snyk-security:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # ✅ Ensure consistency with build
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Check if SNYK_TOKEN is Set
        run: |
          if [ -z "${{ secrets.SNYK_TOKEN }}" ]; then
            echo "SNYK_TOKEN is not set, skipping Snyk step."
            exit 0
          fi
        shell: bash

      - name: Authenticate with Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk auth $SNYK_TOKEN || (echo "Snyk auth failed, skipping..." && exit 0)

      - name: Run Snyk Security Test (Non-Blocking)
        run: |
          snyk test --severity-threshold=high || echo "Snyk test found issues, continuing..."

      - name: Monitor Snyk for Continuous Scanning (Non-Blocking)
        run: |
          snyk monitor || echo "Snyk monitor failed, continuing..."
